[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "src/=src/",
    "test/=test/",
    "script/=script/"
]
optimizer = true
optimizer_runs = 200

# The following settings are critical because without them, CREATE2 same argument assumptions are broken if new
# Foundry libraries are added to the repository over time, via forge install. Forge build generates a different
# bytecode for a contract if a new foundry library is installed. Also, the metadata hash is included as part of
# the bytecode by default, which can prevent deterministic deployments with CREATE2.

solc = "0.8.20"
evm_version = "london"  # Set specific EVM version; both Sepolia and Holesky testnets use London
bytecode_hash = "none"  # Disable bytecode hash; this is necessary for consistent deployed bytecode
cbor_metadata = false   # Disable CBOR metadata
